language: python
python:
- "3.6"
# setup environment
env:
- DJANGO_VERSION=2.1.3

services:
- postgresql

addons:
 postgresql: '9.6'

# install dependencies
install:
- pip3 install -r requirements.txt


# run test scripts
script:
- echo 'travis up and running'

# run coveralls after successful tests
after_success:
- coveralls
