# Generated by Django 2.1.3 on 2018-12-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20181210_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subscribed_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_subscribed_in_app',
            field=models.BooleanField(default=False),
        ),
    ]
