<<<<<<< HEAD
# Generated by Django 2.1.2 on 2018-12-13 10:36
=======
# Generated by Django 2.1.2 on 2018-12-12 17:36
>>>>>>> ce71ac7... [FEATURE #161966915] setup userprofiles app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
<<<<<<< HEAD
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('image', models.CharField(default='', max_length=255)),
                ('birthday', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('bio', models.TextField(default='')),
=======
                ('bio', models.CharField(default='', max_length=255)),
                ('birthday', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
>>>>>>> ce71ac7... [FEATURE #161966915] setup userprofiles app
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
