# Generated by Django 2.1.2 on 2018-12-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(default='', max_length=500),
        ),
    ]
