# Generated by Django 2.1.4 on 2018-12-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181220_1206'),
        ('articles', '0002_auto_20181218_1245'),
    ]

    operations = [
    ]
